ALTER TABLE IF EXISTS "deliveryman_documents"
  ADD COLUMN IF NOT EXISTS "document_number" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "full_name" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "cpf" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "cnh_type" TEXT;
